version: 2.1

executors:
  build-test-and-release:
    docker:
      - image: circleci/node:10.15.3
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test

    working_directory: ~/repo

jobs:
  build:
    executor: build-test-and-release
    steps:
      - checkout
      - run:
          name: Build project
          command: mkdir base && mv ./* ./base

      - run:
          name: Copy package.json
          command: cd .. && cp base/config/package.json ./package.json

      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Setup
          command: node base/setup.js

      - run:
          name: Typescript typings check
          command: yarn type-check

      - run:
          name: Test
          command: yarn test

      - run:
          name: Lint
          command: yarn lint

      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build-test-and-release:
    jobs:
      - build
